backend:
    name: github
    repo: wphestiraid/blog-posts

media_folder: media

collections:
    - name: post
      label: Post
      folder: posts
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Body", name: "body", widget: "markdown"}
        - {label: "Tags", name: "tags", widget: "list"}
