backend:
    name: github
    repo: wphestiraid/netlify-cms-test

media_folder: static/img
public_folder: /img

collections:
    - name: blog
      label: Blog
      folder: posts
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Description", name: "description", widget: "text"}
        - {label: "Body", name: "body", widget: "markdown"}
        - {label: "Tags", name: "tags", widget: "list"}
